services:
  app:
    build: .
    image: spring-demo-app
    container_name: spring-demo-project-app
    ports:
      - "3002:3002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/spring-demo-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    container_name: spring-demo-project-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: spring-demo-project
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spring-demo-project"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: