spring.application.name=spring-boot

spring.datasource.url=jdbc:postgresql://localhost:5432/spring-demo-project
spring.datasource.username=postgres
spring.datasource.password=tiger

server.port=3002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true