spring.application.name=spring-boot
spring.datasource.url= jdbc:postgresql://database:5432/spring-demo-project
spring.datasource.username=postgres
spring.datasource.password=pass
server.port=3002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect